### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by gildasfleury-pro** [gildasfleury/SEBC#1]

**Comment by mfernest** [comment]
See commit [7b179d6](https://github.com/gildasfleury/SEBC/commit/7b179d640e96d63398625717d9d627ec286137da). Replication is complete once the slave is waiting for the master to send the next event.

**Comment by mfernest** [comment]
See commit [8934116](https://github.com/gildasfleury/SEBC/commit/89341162f241e510a461b19fb6bdf8372604ee82).

**Comment by mfernest** [comment]
It looks like you ran through this portion a few times. I give credit for the effort here even though the submitted work isn't complete.
